import { NextResponse } from "next/server";
import { db } from "@/lib/db";
import { auth } from "@/lib/auth";
import { checkGoalsForToday } from "@/app/api/goals/check/goal-service";

// GET /api/goals/daily - Kullanıcının günlük hedeflerini döner
export async function GET(request: Request) {
  try {
    const session = await auth();
    if (!session?.user?.id) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const userId = session.user.id as string;
    const { searchParams } = new URL(request.url);
    const dateParam = searchParams.get("date");

    const targetDate = dateParam
      ? new Date(dateParam)
      : new Date();
    targetDate.setHours(0, 0, 0, 0);

    // Get or create daily goals
    let goals = await db.dailyGoal.findMany({
      where: {
        userId,
        date: targetDate,
      },
      orderBy: {
        goalType: "asc",
      },
    });

    // If no goals exist for today, create them automatically
    if (goals.length === 0) {
      try {
        goals = await createAutoGoals(userId, targetDate);
      } catch (createError: any) {
        // If goals were created by another request, fetch them again
        if (createError?.code === "P2002" || createError?.message?.includes("Unique constraint")) {
          goals = await db.dailyGoal.findMany({
            where: {
              userId,
              date: targetDate,
            },
            orderBy: {
              goalType: "asc",
            },
          });
        } else {
          throw createError;
        }
      }
    }

    // Update goals with current progress (this ensures currentValue and completed are up-to-date)
    try {
      await checkGoalsForToday({ userId, date: targetDate });
      // Fetch updated goals
      goals = await db.dailyGoal.findMany({
        where: {
          userId,
          date: targetDate,
        },
        orderBy: {
          goalType: "asc",
        },
      });
    } catch (error) {
      // If goal check fails, still return the goals we have
      console.error("Error updating goal progress:", error);
    }

    return NextResponse.json({ goals });
  } catch (error) {
    console.error("Error fetching daily goals:", error);
    const errorMessage = error instanceof Error ? error.message : "Günlük hedefler yüklenirken bir hata oluştu";
    return NextResponse.json(
      { error: errorMessage },
      { status: 500 }
    );
  }
}

// POST /api/goals/daily - Yeni günlük hedef oluşturur
export async function POST(request: Request) {
  try {
    const session = await auth();
    if (!session?.user?.id) {
      return NextResponse.json({ error: "Unauthorized" }, { status: 401 });
    }

    const userId = session.user.id as string;
    const body = await request.json();
    const { goalType, targetValue, date } = body;

    if (!goalType || !targetValue) {
      return NextResponse.json(
        { error: "goalType ve targetValue gerekli" },
        { status: 400 }
      );
    }

    const targetDate = date ? new Date(date) : new Date();
    targetDate.setHours(0, 0, 0, 0);

    // Check if goal already exists
    const existing = await db.dailyGoal.findUnique({
      where: {
        userId_date_goalType: {
          userId,
          date: targetDate,
          goalType: goalType as any,
        },
      },
    });

    if (existing) {
      return NextResponse.json(
        { error: "Bu hedef zaten mevcut" },
        { status: 400 }
      );
    }

    const goal = await db.dailyGoal.create({
      data: {
        userId,
        date: targetDate,
        goalType: goalType as any,
        targetValue: parseInt(targetValue),
        autoGenerated: false,
      },
    });

    return NextResponse.json({ goal });
  } catch (error) {
    console.error("Error creating daily goal:", error);
    return NextResponse.json(
      { error: "Günlük hedef oluşturulurken bir hata oluştu" },
      { status: 500 }
    );
  }
}

// Helper function to create auto goals
async function createAutoGoals(userId: string, date: Date) {
  // Get user's recent activity (last 7 days)
  const sevenDaysAgo = new Date(date);
  sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);

  const dateEnd = new Date(date);
  dateEnd.setHours(23, 59, 59, 999);

  const recentAttempts = await db.quizAttempt.findMany({
    where: {
      userId,
      completedAt: {
        gte: sevenDaysAgo,
        lt: dateEnd,
      },
    },
  });

  // Calculate averages
  const avgQuizCount = recentAttempts.length / 7; // per day
  const avgScore =
    recentAttempts.length > 0
      ? recentAttempts.reduce((sum: number, a: { score: number }) => sum + a.score, 0) /
        recentAttempts.length
      : 0;

  // Get unique topics from recent attempts
  const uniqueTopics = new Set(
    recentAttempts
      .map((a: { topic: string | null | undefined }) => a.topic)
      .filter((topic: string | null | undefined): topic is string => topic !== null && topic !== undefined)
  );
  const avgTopicCount = uniqueTopics.size / 7; // unique topics per day

  // Get user's current streak
  const userStreak = await db.userStreak.findUnique({
    where: { userId },
  });

  // Determine goal values
  let testCountGoal = 1; // default for new users
  let scoreGoal = 60; // default
  let topicCompleteGoal = 1; // default for new users
  let streakMaintainGoal = 1; // always 1 to maintain streak

  if (recentAttempts.length > 0) {
    // Active user - set goals based on average + 20% increase
    testCountGoal = Math.max(1, Math.ceil(avgQuizCount * 1.2));
    scoreGoal = Math.min(100, Math.ceil(avgScore * 1.05));
    topicCompleteGoal = Math.max(1, Math.ceil(avgTopicCount * 1.2));
  }

  // If user has a streak, set maintain goal to current streak value
  if (userStreak && userStreak.currentStreak > 0) {
    streakMaintainGoal = userStreak.currentStreak;
  }

  // Create 4 personalized goals
  // Use createMany with skipDuplicates to avoid race conditions
  try {
    await db.dailyGoal.createMany({
      data: [
        {
          userId,
          date,
          goalType: "test_count",
          targetValue: testCountGoal,
          autoGenerated: true,
        },
        {
          userId,
          date,
          goalType: "score_target",
          targetValue: scoreGoal,
          autoGenerated: true,
        },
        {
          userId,
          date,
          goalType: "topic_complete",
          targetValue: topicCompleteGoal,
          autoGenerated: true,
        },
        {
          userId,
          date,
          goalType: "streak_maintain",
          targetValue: streakMaintainGoal,
          autoGenerated: true,
        },
      ],
      skipDuplicates: true,
    });
  } catch (error) {
    // If createMany fails, try individual creates
    console.error("Error creating goals with createMany:", error);
    await Promise.all([
      db.dailyGoal.upsert({
        where: {
          userId_date_goalType: {
            userId,
            date,
            goalType: "test_count",
          },
        },
        create: {
          userId,
          date,
          goalType: "test_count",
          targetValue: testCountGoal,
          autoGenerated: true,
        },
        update: {},
      }),
      db.dailyGoal.upsert({
        where: {
          userId_date_goalType: {
            userId,
            date,
            goalType: "score_target",
          },
        },
        create: {
          userId,
          date,
          goalType: "score_target",
          targetValue: scoreGoal,
          autoGenerated: true,
        },
        update: {},
      }),
      db.dailyGoal.upsert({
        where: {
          userId_date_goalType: {
            userId,
            date,
            goalType: "topic_complete",
          },
        },
        create: {
          userId,
          date,
          goalType: "topic_complete",
          targetValue: topicCompleteGoal,
          autoGenerated: true,
        },
        update: {},
      }),
      db.dailyGoal.upsert({
        where: {
          userId_date_goalType: {
            userId,
            date,
            goalType: "streak_maintain",
          },
        },
        create: {
          userId,
          date,
          goalType: "streak_maintain",
          targetValue: streakMaintainGoal,
          autoGenerated: true,
        },
        update: {},
      }),
    ]);
  }

  // Fetch and return the created goals
  const createdGoals = await db.dailyGoal.findMany({
    where: {
      userId,
      date,
    },
    orderBy: {
      goalType: "asc",
    },
  });

  return createdGoals;
}

