"use client";

import { useEffect, useRef, useState } from "react";
import { useSession } from "next-auth/react";
import { useRouter } from "next/navigation";
import { Target, Flame, Calendar } from "lucide-react";
import { Card, CardContent, CardHeader, CardTitle } from "@/app/components/ui/Card";
import { Button } from "@/app/components/ui/Button";
import { DailyGoalCard } from "@/app/components/goals/DailyGoalCard";

interface DailyGoal {
  id: string;
  goalType: "test_count" | "topic_complete" | "score_target" | "streak_maintain";
  targetValue: number;
  currentValue: number;
  completed: boolean;
  completedAt: string | null;
  autoGenerated: boolean;
  date: string;
}

interface UserStreak {
  currentStreak: number;
  longestStreak: number;
  totalDaysActive: number;
}

const goalTypeLabels: Record<DailyGoal["goalType"], string> = {
  test_count: "Test Çöz",
  topic_complete: "Konu Tamamla",
  score_target: "Skor Hedefi",
  streak_maintain: "Streak Devam",
};

export default function GoalsPage() {
  const { data: session, status } = useSession();
  const router = useRouter();
  const [loading, setLoading] = useState(true);
  const [goals, setGoals] = useState<DailyGoal[]>([]);
  const [streak, setStreak] = useState<UserStreak | null>(null);
  const completedGoalIds = useRef<Set<string>>(new Set());
  const initialisedRef = useRef(false);

  useEffect(() => {
    if (status === "unauthenticated") {
      router.push("/login");
    } else if (status === "authenticated") {
      fetchGoals();
      fetchStreak();
    }
  }, [status, router]);

  const fetchGoals = async () => {
    try {
      const response = await fetch("/api/goals/daily");
      const data = await response.json();

      if (response.ok) {
        setGoals(data.goals || []);
      }
    } catch (error) {
      console.error("Error fetching goals:", error);
    } finally {
      setLoading(false);
    }
  };

  const fetchStreak = async () => {
    try {
      // Streak will be fetched from user profile or a dedicated endpoint
      // For now, we'll get it from the badges/user endpoint or create a dedicated one
      const response = await fetch("/api/badges/user");
      // Streak info might be in user stats, for now we'll use a placeholder
    } catch (error) {
      console.error("Error fetching streak:", error);
    }
  };


  useEffect(() => {
    if (!initialisedRef.current) {
      completedGoalIds.current = new Set(
        goals.filter((goal) => goal.completed).map((goal) => goal.id)
      );
      initialisedRef.current = true;
      return;
    }

    const newlyCompleted = goals.filter(
      (goal) => goal.completed && !completedGoalIds.current.has(goal.id)
    );

    if (newlyCompleted.length > 0) {
      newlyCompleted.forEach((goal) => completedGoalIds.current.add(goal.id));
      // Celebration overlay removed - no extra alerts needed
    }
  }, [goals]);

  if (loading || !session) {
    return (
      <div className="flex items-center justify-center min-h-[400px]">
        <div className="flex flex-col items-center gap-4">
          <div className="w-12 h-12 border-4 border-blue-500 border-t-transparent rounded-full animate-spin dark:border-blue-400"></div>
          <p className="text-gray-600 dark:text-gray-400">Yükleniyor...</p>
        </div>
      </div>
    );
  }

  const completedGoals = goals.filter((g) => g.completed);
  const activeGoals = goals.filter((g) => !g.completed);

  return (
    <div className="space-y-6 md:space-y-8 animate-fade-in pb-8">
      {/* Header */}
      <div className="flex flex-col md:flex-row md:items-center md:justify-between gap-4">
        <div>
          <h1 className="text-4xl md:text-5xl font-display font-bold bg-gradient-to-r from-blue-600 via-indigo-600 to-cyan-600 bg-clip-text text-transparent mb-2">
            Günlük Hedefler
          </h1>
          <p className="text-gray-600 dark:text-gray-400 text-lg font-medium">
            Günlük hedeflerinizi belirleyin ve ilerlemenizi takip edin
          </p>
        </div>
      </div>

      {/* Streak Display */}
      {streak && (
        <Card variant="elevated" className="border border-orange-200 dark:border-orange-800 bg-gradient-to-br from-orange-50 to-red-50 dark:from-orange-950/30 dark:to-red-950/30">
          <CardContent className="p-6">
            <div className="flex items-center justify-between">
              <div className="flex items-center gap-4">
                <div className="w-16 h-16 rounded-full bg-gradient-to-br from-orange-500 to-red-500 flex items-center justify-center">
                  <Flame className="h-8 w-8 text-white" />
                </div>
                <div>
                  <p className="text-sm text-gray-600 dark:text-gray-400 mb-1">
                    Günlük Streak
                  </p>
                  <p className="text-3xl font-bold text-gray-900 dark:text-gray-100">
                    {streak.currentStreak} gün
                  </p>
                  <p className="text-xs text-gray-500 dark:text-gray-400 mt-1">
                    En uzun: {streak.longestStreak} gün
                  </p>
                </div>
              </div>
              <div className="text-right">
                <p className="text-sm text-gray-600 dark:text-gray-400">
                  Toplam Aktif Gün
                </p>
                <p className="text-2xl font-bold text-gray-900 dark:text-gray-100">
                  {streak.totalDaysActive}
                </p>
              </div>
            </div>
          </CardContent>
        </Card>
      )}

      {/* Active Goals */}
      {activeGoals.length > 0 && (
        <div>
          <h2 className="text-2xl font-bold text-gray-900 dark:text-gray-100 mb-4">
            Aktif Hedefler
          </h2>
          <div className="grid md:grid-cols-2 gap-4">
            {activeGoals.map((goal) => (
              <DailyGoalCard key={goal.id} goal={goal} />
            ))}
          </div>
        </div>
      )}

      {/* Completed Goals */}
      {completedGoals.length > 0 && (
        <div>
          <h2 className="text-2xl font-bold text-gray-900 dark:text-gray-100 mb-4">
            Tamamlanan Hedefler
          </h2>
          <div className="grid md:grid-cols-2 gap-4">
            {completedGoals.map((goal) => (
              <DailyGoalCard key={goal.id} goal={goal} />
            ))}
          </div>
        </div>
      )}

      {/* No Goals */}
      {goals.length === 0 && (
        <Card variant="elevated">
          <CardContent className="py-12 text-center">
            <Target className="h-16 w-16 text-gray-400 dark:text-gray-600 mx-auto mb-4" />
            <p className="text-gray-600 dark:text-gray-400 font-medium mb-2">
              Henüz hedef yok
            </p>
            <p className="text-sm text-gray-500 dark:text-gray-500">
              İlk hedefinizi oluşturarak başlayın!
            </p>
          </CardContent>
        </Card>
      )}
    </div>
  );
}

