"use client";

import { Target, CheckCircle, Clock, TrendingUp } from "lucide-react";
import { Card, CardContent } from "@/app/components/ui/Card";

interface DailyGoal {
  id: string;
  goalType: "test_count" | "topic_complete" | "score_target" | "streak_maintain";
  targetValue: number;
  currentValue: number;
  completed: boolean;
  completedAt: string | null;
  autoGenerated: boolean;
}

interface DailyGoalCardProps {
  goal: DailyGoal;
}

const goalTypeLabels = {
  test_count: "Test Çöz",
  topic_complete: "Konu Tamamla",
  score_target: "Skor Hedefi",
  streak_maintain: "Streak Devam",
};

const goalTypeIcons = {
  test_count: Target,
  topic_complete: CheckCircle,
  score_target: TrendingUp,
  streak_maintain: Clock,
};

export function DailyGoalCard({ goal }: DailyGoalCardProps) {
  const Icon = goalTypeIcons[goal.goalType];
  const progress = Math.min((goal.currentValue / goal.targetValue) * 100, 100);
  const isCompleted = goal.completed;

  return (
    <Card
      variant="elevated"
      className={`overflow-hidden transition-all duration-200 ${
        isCompleted
          ? "border-2 border-green-500 dark:border-green-400 bg-green-50 dark:bg-green-950/30"
          : "border border-gray-200 dark:border-gray-800"
      } hover:shadow-lg`}
    >
      <CardContent className="p-6 pt-8">
        <div className="flex items-start gap-4">
          <div
            className={`w-12 h-12 rounded-xl flex items-center justify-center flex-shrink-0 ${
              isCompleted
                ? "bg-gradient-to-br from-green-500 to-emerald-500"
                : "bg-gradient-to-br from-blue-500 to-cyan-500"
            }`}
          >
            <Icon className="h-6 w-6 text-white" />
          </div>

          <div className="flex-1 min-w-0">
            <div className="flex items-center justify-between mb-4">
              <h3 className="font-bold text-gray-900 dark:text-gray-100">
                {goalTypeLabels[goal.goalType]}
              </h3>
              {isCompleted && (
                <CheckCircle className="h-5 w-5 text-green-500 flex-shrink-0" />
              )}
            </div>

            <div className="mb-3">
              <div className="flex items-center justify-between mb-1">
                <span className="text-sm text-gray-600 dark:text-gray-400">
                  {goal.currentValue} / {goal.targetValue}
                </span>
                <span className="text-sm font-semibold text-gray-700 dark:text-gray-300">
                  %{Math.round(progress)}
                </span>
              </div>
              <div className="w-full bg-gray-200 dark:bg-gray-700 rounded-full h-2 overflow-hidden">
                <div
                  className={`h-2 rounded-full transition-all duration-300 ${
                    isCompleted
                      ? "bg-gradient-to-r from-green-500 to-emerald-500"
                      : "bg-gradient-to-r from-blue-500 to-cyan-500"
                  }`}
                  style={{ width: `${progress}%` }}
                />
              </div>
            </div>

            {goal.autoGenerated && (
              <p className="text-xs text-gray-500 dark:text-gray-400 mt-2">
                Sistem tarafından otomatik oluşturuldu
              </p>
            )}
          </div>
        </div>
      </CardContent>
    </Card>
  );
}

